name: Run Build Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  build_tests:
    uses: OpenVoiceOS/gh-automations/.github/workflows/build-tests.yml@dev
    secrets: inherit
    with:
      system_deps: 'swig libssl-dev portaudio19-dev libpulse-dev'
      install_extras: 'mycroft,plugins,skills-essential,test'
      test_path: 'test/unittests'
