name: Coverage Report

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  coverage:
    uses: OpenVoiceOS/gh-automations/.github/workflows/coverage.yml@dev
    secrets: inherit
    with:
      system_deps: 'python3-dev swig libssl-dev portaudio19-dev libpulse-dev'
      install_extras: '.[mycroft,plugins,skills-essential,padatious,test]'
      test_path: 'test/unittests'
      coverage_source: 'ovos_core'
      deploy_pages: true
      gh_pages_branch: 'gh-pages'
