name: Run Integration Tests
on:
  pull_request:
    branches:
      - dev
      - master
    paths-ignore:
      - 'ovos_core/version.py'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'readme.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  integration_tests:
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.9]
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig
          python -m pip install build wheel uv
      - name: Install test dependencies
        run: |
          uv pip install -r requirements/tests.txt
          uv pip install ./test/integrationtests/common_query/ovos_tskill_fakewiki
      - name: Install core repo
        run: |
          uv pip install -e .[plugins]
      - name: Run integration tests
        run: |
          pytest test/integrationtests
