name: Run License Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  license_tests:
    uses: OpenVoiceOS/gh-automations/.github/workflows/license-check.yml@dev
    with:
      install_extras: '[mycroft,lgpl,skills-essential]'
      system_deps: 'swig libfann-dev portaudio19-dev libpulse-dev'
      exclude_packages: '^(precise-runner|fann2|ovos-adapt-parser|ovos-padatious|tqdm|bs4|sonopy|caldav|recurring-ical-events|x-wr-timezone|zeroconf|mutagen|attrs|phoonnx).*'
