name: Run Mycroft Tests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'ovos_core/version.py'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'readme.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  mycroft_tests:
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.9]
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig libssl-dev portaudio19-dev libpulse-dev
          python -m pip install build wheel uv
      - name: Install test dependencies
        run: |
          uv pip install --system -r requirements/tests.txt
      - name: Install core repo
        run: |
          uv pip install --system -e .[mycroft,plugins,deprecated]
      - name: Run mycroft compat tests
        run: |
          pytest test/backwards_compat