name: Run PipAudit

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  pip_audit:
    uses: OpenVoiceOS/gh-automations/.github/workflows/pip-audit.yml@dev
    secrets: inherit
    with:
      system_deps: 'swig libssl-dev'
      install_extras: '[skills-essential]'
      ignore_vulns: |
        GHSA-r9hx-vwmv-q579
        GHSA-fpfv-jqm9-f5jm
