name: Sync Translations

on:
  push:
    branches: [dev]
    paths:
      - 'ovos_core/intent_services/locale/**'
  workflow_dispatch:

jobs:
  sync_translations:
    if: github.actor == 'gitlocalize-app[bot]' || github.event_name == 'workflow_dispatch'
    uses: OpenVoiceOS/gh-automations/.github/workflows/sync-translations.yml@dev
    secrets: inherit
    with:
      branch: 'dev'
      locale_path: 'ovos_core/intent_services/locale'
